// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeaMoneyApp.DataAccess;

#nullable disable

namespace SeaMoneyApp.DataAccess.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20260106011230_RenameTableContracts")]
    partial class RenameTableContracts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<short>("ToursInRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tours_in_rank");

                    b.Property<int?>("position_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("position_id");

                    b.ToTable("table_accounts");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.ChangeRubToDollar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("table_rub_to_dollar");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("begin_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.HasKey("Id");

                    b.ToTable("table_contracts");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.PersonalBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("PersonalBonusValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("personal_bonus");

                    b.Property<short>("ToursInRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tours_in_rank");

                    b.Property<int?>("position_id")
                        .HasColumnType("INTEGER");

                    b.Property<short>("year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("position_id");

                    b.ToTable("table_personal_bonuses");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("table_positions");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("BasicWage")
                        .HasColumnType("TEXT")
                        .HasColumnName("basic_wage");

                    b.Property<decimal>("CompanyBonus")
                        .HasColumnType("TEXT")
                        .HasColumnName("company_bonus");

                    b.Property<decimal>("CrewOvertime")
                        .HasColumnType("TEXT")
                        .HasColumnName("crew_overtime");

                    b.Property<decimal>("FidelityBonus")
                        .HasColumnType("TEXT")
                        .HasColumnName("fidelity_bonus");

                    b.Property<decimal>("PerformanceBonus")
                        .HasColumnType("TEXT")
                        .HasColumnName("performance_bonus");

                    b.Property<decimal>("Vacation")
                        .HasColumnType("TEXT")
                        .HasColumnName("vacation");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int?>("position_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("position_id");

                    b.ToTable("table_salaries");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.WageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountInRub")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_in_rub");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<short>("ToursInRank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tours_in_rank");

                    b.Property<int?>("account_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("change_rub_to_dollar_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("contract_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("position_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("account_id");

                    b.HasIndex("change_rub_to_dollar_id");

                    b.HasIndex("contract_id");

                    b.HasIndex("position_id");

                    b.ToTable("table_wage_log");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.Account", b =>
                {
                    b.HasOne("SeaMoneyApp.DataAccess.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("position_id");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.PersonalBonus", b =>
                {
                    b.HasOne("SeaMoneyApp.DataAccess.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("position_id");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.Salary", b =>
                {
                    b.HasOne("SeaMoneyApp.DataAccess.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("position_id");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("SeaMoneyApp.DataAccess.Models.WageLog", b =>
                {
                    b.HasOne("SeaMoneyApp.DataAccess.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("account_id");

                    b.HasOne("SeaMoneyApp.DataAccess.Models.ChangeRubToDollar", "ChangeRubToDollar")
                        .WithMany()
                        .HasForeignKey("change_rub_to_dollar_id");

                    b.HasOne("SeaMoneyApp.DataAccess.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("contract_id");

                    b.HasOne("SeaMoneyApp.DataAccess.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("position_id");

                    b.Navigation("Account");

                    b.Navigation("ChangeRubToDollar");

                    b.Navigation("Contract");

                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
